# Generated by Django 6.0.5 on 2026-05-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acciones_modificads', models.TextField()),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.user')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_sesiones', models.IntegerField(default=3)),
                ('tiempo_inactividad', models.IntegerField(default=5)),
                ('tiempo_expiracion', models.IntegerField(default=10)),
                ('tiempo_preservacion', models.IntegerField(default=5)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.user')),
            ],
        ),
    ]
