# Generated by Django 6.0.5 on 2026-05-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionactiva',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
