# Generated by Django 6.0.5 on 2026-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_alter_sesionactiva_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionactiva',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
